-d C:\Users\redsq\Documents\logisim\Tang nano 9k\CPU5_5\impl\gwsynthesis\CPU5_5.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\redsq\Documents\logisim\Tang nano 9k\CPU5_5\src\CPU5_5.cst
-cfg C:\Users\redsq\Documents\logisim\Tang nano 9k\CPU5_5\impl\pnr\device.cfg
-sdc C:\Users\redsq\Documents\logisim\Tang nano 9k\CPU5_5\src\CPU5_5.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
